### PR TITLE
added ignoreDataErrors option to RelayConnection fetcher

### PR DESCRIPTION
**Pull request by MichiTha**
Sometimes GraphQL backends will send errors that should not stop the generation of the complete sitemap.
For that, an ignoreDataErrors flag could be used in the RelayConnectionFetcher.

### CODE REVIEW

**Comment by MichiTha** [comment]
a more advanced approach could be the option for a custom onError Handler.

**Comment by sambou** [comment]
Thanks for opening this PR! Error handling is very primitive at the moment, so any work there is appreciated 🙂

I think you should also add a `try / catch` around `return getConnection(data)` in [line 93](https://github.com/tristramjs/tristram/pull/15/files#diff-83053532852658168c27b202bb7c36f3R93) and retry similar to the logic above.

I would also rename the flag to `ignoreNonCriticalErrors` to better reflect the function of the flag.

Regarding the more advanced idea of custom error handlers: I can't really think of a way to implement this without leaking too much internal details out to the client. Feel free to open a PR if you have an idea!

So far, I like the flag better because it's simpler and it seems to solve the issue of the `RelayConnectionFetcher` failing to eagerly 👍

**Comment by MichiTha** [comment]
I think that there should be a better differentiation between http-level erros and graphQL-level errors.
As i think retry just make sense on https level errors.

The current error handling implementation of `RelayConnectionFetcher` ignores http-level errors and just looks on valid req.body, which is basically just valid JSON. In most cases, errors in this JSON won't go away with retrys, because they are mostly caues by wrong requests or missing data in the backend.

.... then there are some GraphQL services that will send 404 or 400 status and some errors, just if a small part of the query could not be resolved. So also there it would be bad if the complete response body would be wasted.

**Comment by MichiTha** [comment]
I think GraphQL errors should just be ignored, as they can be handled by the transformer.

**Comment by sambou** [comment]
> The current error handling implementation of RelayConnectionFetcher ignores http-level errors and just looks on valid req.body, which is basically just valid JSON. In most cases, errors in this JSON won't go away with retrys, because they are mostly caues by wrong requests or missing data in the backend.

Agreed, we should add this distinction. Probably it makes sense to retry on server errors and errors like `429` (too many requests) and fail immediately on everything else on the HTTP level.

Do you have an idea for handling Graphql errors? Maybe we could allow clients to pass a custom function instead of the generic log statement we currently have. This function could then be application-specific, and either log or throw an error in case the error from the Graphql API was more severe. I'm thinking of sth. like this:

```javascript
async fetchConnection(): Promise<GraphQlConnection<T>> {
    const {
        url, query, variables, getConnection, logErrors, handleErrors
    } = this;
    let retries = 0;
    const options = {
        method: 'POST',
        headers: {
            'content-type': 'application/json',
        },
        body: JSON.stringify({ query, variables }),
    };

    while (retries < this.maxRetries) {
        const res = await fetch(url, options);
        
        // retry on TOO MANY REQUESTS and server errors
        if (res.status === 429 || res.status > 499) {
            retries = retries + 1;
        } else {
            const data = await res.json();
            if (data.errors && Array.isArray(data.errors)) {
                handleErrors && handleErrors(data);
            }
            return getConnection(data);
        }
    }

    throw new Error(`Error fetching connection, tried ${retries} times.`);
}
```

What do you think?

**Comment by MichiTha** [comment]
> We could also do this and just delete the part in the current implementation 🙂

just made a PR for that https://github.com/tristramjs/tristram/pull/15

**Pull request closed without merging**
